name: GestureTV
fileGroups:
  - configs
configFiles:
  Debug: configs/Base.xcconfig
  Release: configs/Base.xcconfig
targets:
  GestureTV:
    platform: tvOS
    type: framework
    configFiles:
      Debug: configs/GestureTV.xcconfig
      Release: configs/GestureTV.xcconfig
    sources: 
      - GestureTV
    prebuildScripts:
      - script: |
            ./Pods/Sourcery/bin/sourcery
  GestureTVExample:
    platform: tvOS
    type: application
    sources: 
      - GestureTVExample
    configFiles:
      Debug: configs/GestureTVExample.xcconfig
      Release: configs/GestureTVExample.xcconfig
    dependencies:
      - target: GestureTV

